(ns district-voting.constants)

(def candidates
  [{:title "Candidate 1"
    :description "Lorem ipsum dolor sit amet, solet vitae expetenda quo ad, et fugit facilisi consectetuer his, an volumus sapientem cum. Ea facete verterem ius, qui vero utroque cu. Eam ei veritus docendi philosophia, dicat inermis quo ne. Eos ad facer laboramus, nam an consul neglegentur.\n\nDelenit fierent efficiendi nam ei. Ex per dicta error tollit. Pri mucius consectetuer eu, ferri labores duo ex. Quod tation vocibus nam ut, his ex duis tacimates. Mei ne ubique essent nominati, et facilisis consectetuer eum. Te mea libris meliore, vel eius fastidii quaestio ut, mazim liber fabellas quo ad.\n\nOdio postulant nec an. Sea an audire sensibus. Id tota placerat vituperatoribus nec, quem alterum an mei. Delenit sapientem cum eu, at eam commune iracundia.\n\nCu has saepe officiis maluisset. Est essent tritani definitiones eu, te mei brute consul libris, inani commodo gubergren id vel. Clita regione nusquam cu has, mel eros consectetuer no. Vel id augue voluptaria, quidam integre detracto at vix. Eum at mollis vivendo ullamcorper, iisque maiorum fierent his te. Ius te novum primis latine.\n\nDeleniti apeirian no eum, ut eum vide feugait disputationi, sea ad modus tantas instructior. Cum ea nibh tritani. Et nam tale dico iracundia. Est tollit scaevola sententiae ea, ea animal assentior vulputate sea. Minim iracundia delicatissimi at vel."}
   {:title "Candidate 2"
    :description "Lorem ipsum dolor sit amet, solet vitae expetenda quo ad, et fugit facilisi consectetuer his, an volumus sapientem cum. Ea facete verterem ius, qui vero utroque cu. Eam ei veritus docendi philosophia, dicat inermis quo ne. Eos ad facer laboramus, nam an consul neglegentur.\n\nDelenit fierent efficiendi nam ei. Ex per dicta error tollit. Pri mucius consectetuer eu, ferri labores duo ex. Quod tation vocibus nam ut, his ex duis tacimates. Mei ne ubique essent nominati, et facilisis consectetuer eum. Te mea libris meliore, vel eius fastidii quaestio ut, mazim liber fabellas quo ad.\n\nOdio postulant nec an. Sea an audire sensibus. Id tota placerat vituperatoribus nec, quem alterum an mei. Delenit sapientem cum eu, at eam commune iracundia.\n\nCu has saepe officiis maluisset. Est essent tritani definitiones eu, te mei brute consul libris, inani commodo gubergren id vel. Clita regione nusquam cu has, mel eros consectetuer no. Vel id augue voluptaria, quidam integre detracto at vix. Eum at mollis vivendo ullamcorper, iisque maiorum fierent his te. Ius te novum primis latine.\n\nDeleniti apeirian no eum, ut eum vide feugait disputationi, sea ad modus tantas instructior. Cum ea nibh tritani. Et nam tale dico iracundia. Est tollit scaevola sententiae ea, ea animal assentior vulputate sea. Minim iracundia delicatissimi at vel."}
   {:title "Candidate 3"
    :description "Lorem ipsum dolor sit amet, solet vitae expetenda quo ad, et fugit facilisi consectetuer his, an volumus sapientem cum. Ea facete verterem ius, qui vero utroque cu. Eam ei veritus docendi philosophia, dicat inermis quo ne. Eos ad facer laboramus, nam an consul neglegentur.\n\nDelenit fierent efficiendi nam ei. Ex per dicta error tollit. Pri mucius consectetuer eu, ferri labores duo ex. Quod tation vocibus nam ut, his ex duis tacimates. Mei ne ubique essent nominati, et facilisis consectetuer eum. Te mea libris meliore, vel eius fastidii quaestio ut, mazim liber fabellas quo ad.\n\nOdio postulant nec an. Sea an audire sensibus. Id tota placerat vituperatoribus nec, quem alterum an mei. Delenit sapientem cum eu, at eam commune iracundia.\n\nCu has saepe officiis maluisset. Est essent tritani definitiones eu, te mei brute consul libris, inani commodo gubergren id vel. Clita regione nusquam cu has, mel eros consectetuer no. Vel id augue voluptaria, quidam integre detracto at vix. Eum at mollis vivendo ullamcorper, iisque maiorum fierent his te. Ius te novum primis latine.\n\nDeleniti apeirian no eum, ut eum vide feugait disputationi, sea ad modus tantas instructior. Cum ea nibh tritani. Et nam tale dico iracundia. Est tollit scaevola sententiae ea, ea animal assentior vulputate sea. Minim iracundia delicatissimi at vel."}
   {:title "Candidate 4"
    :description "Lorem ipsum dolor sit amet, solet vitae expetenda quo ad, et fugit facilisi consectetuer his, an volumus sapientem cum. Ea facete verterem ius, qui vero utroque cu. Eam ei veritus docendi philosophia, dicat inermis quo ne. Eos ad facer laboramus, nam an consul neglegentur.\n\nDelenit fierent efficiendi nam ei. Ex per dicta error tollit. Pri mucius consectetuer eu, ferri labores duo ex. Quod tation vocibus nam ut, his ex duis tacimates. Mei ne ubique essent nominati, et facilisis consectetuer eum. Te mea libris meliore, vel eius fastidii quaestio ut, mazim liber fabellas quo ad.\n\nOdio postulant nec an. Sea an audire sensibus. Id tota placerat vituperatoribus nec, quem alterum an mei. Delenit sapientem cum eu, at eam commune iracundia.\n\nCu has saepe officiis maluisset. Est essent tritani definitiones eu, te mei brute consul libris, inani commodo gubergren id vel. Clita regione nusquam cu has, mel eros consectetuer no. Vel id augue voluptaria, quidam integre detracto at vix. Eum at mollis vivendo ullamcorper, iisque maiorum fierent his te. Ius te novum primis latine.\n\nDeleniti apeirian no eum, ut eum vide feugait disputationi, sea ad modus tantas instructior. Cum ea nibh tritani. Et nam tale dico iracundia. Est tollit scaevola sententiae ea, ea animal assentior vulputate sea. Minim iracundia delicatissimi at vel."}])
