(ns district-voting.constants)

(defn link [name url]
  [:a {:href url
       :target :_blank}
   name])

(def load-votes-limit 2)

(def candidates
  {3 {:title "1Hive"
      :description [:div "The 1Hive Funding platform would offer a standardized and accountable crowdfunding dapp on top of a curation market. Similar to " [link "Patreon" "https://www.patreon.com/"] " or " [link "Kickstarter" "https://www.kickstarter.com/"] ", an individual or group could champion a project and solicit support from the community to provide funding to bring the idea to market. The platform would support both funding milestones and time-based funding release mechanisms. In addition, early contributors to a project would benefit from the projects future success, so community members have the incentive to find the best projects early and shift their support to those. The result is that quality projects should bubble up and receive the most funding and attention from the community."]}
   18 {:title "Influencer.io"
       :description [:div "As US digital ad spend reaches " [link "$82.86 billion" "https://www.emarketer.com/Article/US-Digital-Ad-Spending-Surpass-TV-this-Year/1014469"] " in 2017 and " [link "47% of online consumers" "https://digiday.com/uk/latest-ad-blocking-report-finds-half-disable-blockers-read-content/"] " use ad blockers, advertisers have been turning to influencer marketing in order to successfully reach their target audience. Influencer marketing can be defined as paying an influencer to advertise your product throughout their social media platforms. Through the Influencer District, advertisers will instantly discover their product’s ideal influencer in order to reach their campaign’s target audience. All of this with no platform fee."]}
   1 {:title "Bounty.io"
      :description "This district will be a one stop shop for startups who are seeking to have bounties completed, and for users who want to complete bounties. The UI will be very intuitive, much like Ethlance. Users will be able to search through available bounties and select those which they want to complete. Upon completion of a bounty they will be paid out and receive rewards. Teams will be able to easily and efficiently pay disburse payments to contributors who have fulfilled the requirements of any bounties. A verification process will be built in to verify that each job was successfully completed."}
   10 {:title "etherAid"
       :description "The EtherAid network will connect willing donors directly with local charities across the world. The network will provide access to real-time emergency funds for those most in need, sourced from the global economy. Operationally, the network can be compared to a crowdfunding marketplace, but with several key distinctions. First, the receiver of funds (i.e. “charities”) would need to be vetted for quality ahead of time. Second, the money trail needs to be fully auditable to prevent fraudulent use of funds. Finally, the sender of funds (i.e. “donors”) will be provided with a certified tax receipt as is customary with charitable donations."}
   17 {:title "Localview"
       :description "Apps and websites like Yelp are good resources to allow residents to access reviews from others in their communities on places and activities in their local city. But the centralized nature leads to flaws, with advertisements competing for space and a focus on quantity of reviews over quality. For reviewers, there is limited pay off for putting together higher quality reviews. Some may even try to branch out to their own blogs/sites but then run into other issues getting value out of their reviews. For those looking to consume reviews, they end up with long lists of low quality reviews or struggle trying to find those community experts. This is where Localview comes into the picture."}
   29 {:title "Decentraland District"
       :description [:div [link "Decentraland" "https://decentraland.org/"] " is an open source initiative to build a traversable virtual reality world. Within Decentraland, habitants can claim land as their own and build anything they wish upon it, from 3D artwork to fully immersive applications such as a VR poker room, for other inhabitants of the world to discover and enjoy. The nature of adjacency of land will lead to particular parcels becoming more desirable than others as a byproduct of their surroundings. A parcel which hosts a heavily trafficked installation will naturally enhance the discoverability of content hosted by neighboring landowners, leading to an appreciation in the inherent value of bordering plots. The Decentraland District will establish a secondary market for land ownership and rentals within the Decentraland virtual world, establishing a focal point for the exchange of parcels and providing a means of price discovery and liquidity for LAND owners."]}})
